Renamed precommit scripts

diff --git a/GitHook/hooks/pre-commit_branch_check b/GitHook/hooks/pre-commit_branch_check
--- a/GitHook/hooks/pre-commit_branch_check
+++ b/GitHook/hooks/pre-commit_branch_check
@@ -16,6 +16,10 @@ elif [[ $signingKey -eq "" ]];
 then
         echo "No signing key found. Check global gitconfig"
         exit 1
+elif [ "$branch" = "master" ]; 
+then
+			  echo "You can't commit directly to master branch"
+			  exit 1
 else
 				exit 0
 fi
